# Generated by Django 2.0.7 on 2018-07-13 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import service_requests.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topics', '0002_tag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0006_auto_20180713_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceFulfillment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('offer completion', 'oc'), ('request completion', 'rc')], max_length=3)),
                ('service_offer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='completions', to='services.ServiceOffer')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('posted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='topics.Category')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Message')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Submitted at')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='service_requests.ServiceFulfillment', verbose_name='Submission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'submission message',
                'verbose_name_plural': 'submission messages',
                'ordering': ['submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Undecided', 'u'), ('Rejected', 'r'), ('Accepted', 'a')], default='u', max_length=2)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='service_requests.ServiceFulfillment', verbose_name='Submission')),
            ],
        ),
        migrations.CreateModel(
            name='SupportingDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Created at')),
                ('document', models.FileField(upload_to=service_requests.models.uuid_filename, verbose_name='Document')),
                ('description', models.CharField(max_length=140, verbose_name='Description')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supporting_documents', to='service_requests.ServiceFulfillment', verbose_name='Submission')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded by')),
            ],
        ),
        migrations.AddField(
            model_name='servicefulfillment',
            name='service_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fulfillment_offers', to='service_requests.ServiceRequest'),
        ),
    ]
