# Generated by Django 2.0.7 on 2018-07-08 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20180707_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceoffer',
            name='price',
            field=models.DecimalField(decimal_places=2, default=40.0, max_digits=4),
        ),
    ]
