# Generated by Django 2.0.7 on 2018-07-09 09:57

from django.db import migrations, models
import services.models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_serviceoffer_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceoffer',
            name='main_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=services.models.get_service_image_path),
        ),
    ]
