# Generated by Django 2.0.7 on 2018-07-10 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_serviceoffer_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceoffer',
            name='status',
            field=models.CharField(choices=[('w', 'draft'), ('r', 'requested'), ('a', 'approved'), ('p', 'published'), ('i', 'inactive'), ('d', 'denied')], max_length=50),
        ),
    ]
