# Generated by Django 2.0.7 on 2018-07-15 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscrowWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('created_on', models.DateField(auto_now=True)),
                ('payed_out', models.BooleanField(default=False)),
                ('payed_on', models.DateField(blank=True, default=None, null=True)),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_payment_holds', to='wallets.Wallet')),
                ('target_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_payment_holds', to='wallets.Wallet')),
            ],
        ),
    ]
