# Generated by Django 2.0.7 on 2018-07-16 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_escrowwallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('p', 'PayPal'), ('b', 'BitPay'), ('c', 'Credit Card')], default='b', max_length=2)),
                ('uid', models.TextField()),
            ],
        ),
    ]
