# Generated by Django 2.0.7 on 2018-07-16 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_auto_20180716_1045'),
        ('wallets', '0003_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='order',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.ServiceOrder'),
        ),
    ]
